<a href="https://colab.research.google.com/github/Xylenox/CAP4630/blob/master/HW_4/HW4_Problem2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Max Pooling

In [0]:
import numpy as np

In [0]:
def maxpooling2d(input_mat, s):
  if input_mat.shape[0] != input_mat.shape[1]:
    raise ValueError("Input Matrix is not square")
  if input_mat.shape[0]%s != 0:
    raise ValueError("Input Matrix size is not divisible by s")
  output_mat = np.zeros((input_mat.shape[0]//s, input_mat.shape[1]//s))
  for x in range(0, output_mat.shape[0], s):
    for y in range(0, output_mat.shape[1], s):
      output_mat[x//s][y//s] = input_mat[x][y]
      for dx in range(0, s):
        for dy in range(0, s):
          if(input_mat[x+dx][y+dy] > output_mat[x//s][y//s]):
            output_mat[x//s][y//s] = input_mat[x+dx][y+dy]
  return output_mat

# Testing

In [4]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  #output_mat = maxpooling2d(input_mat[i], s[i])
  output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")


[[4 2]
 [2 4]]
Correct output!
[[4 2 5]
 [2 4 5]
 [1 3 2]]
Correct output!
