<a href="https://colab.research.google.com/github/Xylenox/CAP4630/blob/master/HW_4/HW4_Problem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Convolution

In [0]:
import numpy as np

In [0]:
def conv2d(input_mat, kernal_mat):
  if input_mat.shape[0] != input_mat.shape[1]:
    raise ValueError("Input Matrix is not square")
  if kernal_mat.shape[0] != kernal_mat.shape[1]:
    raise ValueError("Kernel Matrix is not square")
  output_mat = np.zeros((input_mat.shape[0]-kernal_mat.shape[0]+1, input_mat.shape[1]-kernal_mat.shape[1]+1))
  for x in range(0, output_mat.shape[0]):
    for y in range(0, output_mat.shape[1]):
      for dx in range(0, kernal_mat.shape[0]):
        for dy in range(0, kernal_mat.shape[1]):
          output_mat[x][y] += input_mat[x+dx][y+dy]*kernal_mat[dx][dy]
  return output_mat

# Testing

In [1]:
from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  #output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
    output_mat = []
  else:
    output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")


[[2 4 2]
 [4 2 4]
 [2 4 2]]
Correct output!

[[2 0 0]
 [0 2 0]
 [0 0 2]]
Correct output!

[[ 1 -1  0]
 [-1  1 -1]
 [ 0 -1  1]]
Correct output!

[[4]]
Correct output!

[]
Correct output!

